language: node_js
node_js:
  - '5'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-koa' ]; then cd .. && eval "mv $currentfolder generator-koa" && cd generator-koa; fi

